language: node_js
after_success: bash ./deploy.sh
cache:
  directories:
    - node_modules
env:
  global:
    secure: rLjMFlQ22PmS9wwP15eR0Mj8414mGzcsplr2U6yTKjvAVv9BJCvuKZVAnkXMgBb3D9HLEGNqEz+qS3fNNPAcl5BSwySyDKXFN61mr6C1vLvU/9MYdRqGl1nhZz9pZDrcIHI9HSKYuXliXdA3ZstDNFCStJLo52w1iiCq2CwpgxsNn7hz0jMaWlsyGwlDZQK7VJJCdoptQdnPO8sJa1mEvbMLJ+3FhLG0D6YYI6AOBLc7+QAOzBfa87fPnvzoYYeODoyvtazzMX+WZsDwareS6kVfrE4Swh1ajfKJvfZHyskJw9UuZZMQau1jITYe+PTUrqjpqM55EgEyfd71B6f5Qpsb4xzVSVu3g7/jUdKx5lo3t4Rao67QodAdk4cDQcf08j4d0XRISRRxOdmJjClhT5s0zdR4ttWtk1qjmazwKQ6t+yaA6NNl4igSpWXXzjlLb84HFibDxPm7pIG8w5H1+aqLUYARSo3MBKcL1+BAg0+klAI6l0wGsTKlXhhuxabaN5gxP0DULHIdaCB+gGIDsLgCluQ/v5Lng+PBEk6AlMjc5lgxYvxSFOUi7OdB6h9TQgOeiGyZfX8IaMBpfHyQ/X1MzuiOBnftnJ80b6J1yO4l0gmnbWQvtHL+4urr+kBzq9K2pyYaEYqPceJY47U4LcJY/SWXSXsUyW4sxfqpdow=
